#!/usr/bin/env bash

set -e

if [[ -z "$DOTFILES" ]]; then
  # best way of getting current directory, apparently
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$(pwd)"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.sh"
export PATH="${DOTFILES}/bin:${PATH}"

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

if ! __nan_has "brew"; then
  __nan_echo "Installing Homebrew..."
  curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

  export PATH="/usr/local/bin:$PATH"
fi