#!/usr/bin/env bash

set -e

if [[ -z "$DOTFILES" ]]; then
  # best way of getting current directory, apparently
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$(pwd)"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"
export PATH="${DOTFILES}/bin:${PATH}"

# ============================================================================
# 1. zsh
# ============================================================================

# ============================================================================
# 2. Install Homebrew
# ============================================================================

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

update_shell() {
  local shell_path;
  shell_path="$(which zsh)"

  __nan_echo "Changing your shell to zsh..."
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    __nan_echo "Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells"
  fi
  sudo chsh -s "$shell_path" "$USER"
}

update_shell

if ! __nan_has "brew" ; then
  __nan_echo "Installing Homebrew..."
  curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

  export PATH="/usr/local/bin:$PATH"
fi

# ============================================================================
# 3. Install ASDF
# ============================================================================

bash "${DOTFILES}/bootstrap/asdf"

# ============================================================================
# Install ASDF plugins/languages
# ============================================================================
#
# install_asdf_plugin() {
#   local name="$1"
#
#   if ! asdf plugin-list | grep -Fq "$name"; then
#     asdf plugin-add "$name"
#   fi
# }
#
# install_asdf_plugin "ruby"
# install_asdf_plugin "python"
# # install_asdf_plugin "elixir"
# install_asdf_plugin "nodejs"
#
# install_asdf_language() {
#   local language="$1"
#   local version
#   version="$(asdf list-all "$language" | grep '^[0-9]' | grep -v '[a-z]' | tail -1)"
#
#   if ! asdf list "$language" | grep -Fq "$version"; then
#     asdf install "$language" "$version"
#     asdf global "$language" "$version"
#   fi
# }
#
# # ASDF: Language-specific functions
# gem_install_or_update() {
#   if gem list "$1" --installed > /dev/null; then
#     gem update "$@"
#   else
#     gem install "$@"
#   fi
# }
#
# # ASDF: Install Ruby
# echo "Installing Ruby..."
# install_asdf_language "ruby"
# gem update --system
# gem_install_or_update "bundler"
# number_of_cores=$(sysctl -n hw.ncpu)
# bundle config --global jobs $((number_of_cores - 1))
#
# # ASDF: Install Python - todo
# echo "Installing Python..."
# # install_asdf_language "python"
# asdf install python 3.6.5
# asdf install python 2.7.14
# asdf global python 3.6.5 2.7.14
#
# echo "Installing webshit..."
# bash "$HOME/.asdf/plugins/nodejs/bin/import-release-team-keyring"
# install_asdf_language "nodejs"
