#!/usr/bin/env bash

if [[ -z "$DOTFILES" ]]; then
  # best way of getting current directory, apparently
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$(pwd)"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.sh"
export PATH="${DOTFILES}/bin:${PATH}"

# ============================================================================
# Create paths (slow)
# ============================================================================

mkdir -p -- "${HOME}/.config"

__symlink() {
  __nan_status "Symlinking dotfiles..."

  nan-symlink "zsh/dot.zshenv" ".zshenv"

  __nan_status "Done! [symlink.sh]"
}

__symlink