#!/usr/bin/env bash

if [[ -z "$DOTFILES" ]]; then
  # best way of getting current directory, apparently
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$(pwd)"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"
export PATH="${DOTFILES}/bin:${PATH}"

# ============================================================================
# Create paths (slow)
# ============================================================================

mkdir -p -- "${HOME}/.cache"
mkdir -p -- "${HOME}/.config"

# ============================================================================
# Main
# ============================================================================

__symlink() {
  __nan_status "Symlinking dotfiles..."

  # REQUIRED in ~/ -- ag looks for ~/.agignore LAST and includes it.
  # .ignore files are for project local only
  nan-symlink  "shell/dot.profile" ".profile"

  # REQUIRED in ~/ -- ag looks for ~/.agignore LAST and includes it.
  # .ignore files are for project local only
  nan-symlink  "ag/dot.ignore" ".agignore"

  # universal-ctags
  nan-symlink  "universal-ctags/dot.ctags" ".ctags"

  # XDG-compatible
  # nan-symlink "git/dot.gitconfig" ".config/git/config"
  nan-symlink "git/dot.gitconfig" ".gitconfig"
  nan-symlink "git/dot.gitignore" ".config/git/ignore"

  # (n)vim
  nan-symlink  "vim" ".vim"
  nan-symlink  "vim" ".config/nvim"

  case "$OSTYPE" in
    darwin*)
      nan-symlink "system/macOS/dot.hushlogin" ".hushlogin"
    ;;
  esac

  # Shell
  nan-symlink "zsh/dot.zshenv" ".zshenv"

  __nan_status "Done! [symlink.sh]"
}

__symlink
