#!/usr/bin/env bash

set -e

# =============================================================================
# Require DOTFILES
# =============================================================================

if [[ -z "$DOTFILES" ]]; then
  echo ".dotfiles repo is not set up"
  exit 1
fi
. "${DOTFILES}/lib/pretty.bash"

# Clean room
# reset TERM since we use custom one in iTerm
TERM=xterm-256color

# ============================================================================
# taps
# ============================================================================

# brew services launchctl manager -- no formulae
brew tap homebrew/services
brew tap caskroom/versions
brew tap caskroom/fonts

# ============================================================================
# Meta
# ============================================================================

brew update

# brew cask completion
brew install brew-cask-completion

# ============================================================================
# compilers, tools, and libs
# ============================================================================

brew install automake cmake
brew install coreutils findutils moreutils
brew install libtool
brew install pkg-config

# ============================================================================
# editor
# ============================================================================

brew install neovim

# ============================================================================
# filesystem
# ============================================================================

brew install ack
brew install fasd
brew install fzf
brew install rsync
brew install tree
brew install ripgrep
brew install the_silver_searcher

# ============================================================================
# operations
# ============================================================================

# OpenSSL for some programs, but prefer libressl where possible
brew install openssl

# Too annoying to re-setup ssh-agent since the ssh-add does not have keychain
# access -- disabled:
# ----------------------------------------------------------------------------
# Install a newer version of OpenSSH
# that isn't susceptible to http://www.openssh.com/txt/release-7.1p2
#brew install homebrew/dupes/ssh --with-libressl

# better curl
brew install curl --with-libressl
brew link --force curl

brew install htop --with-ncurses

brew install multitail
brew install nmap
brew install ssh-copy-id
brew install wget
brew install wifi-password
brew install exa

# ============================================================================
# shells
# ============================================================================

brew install bats shellcheck
brew install tmux
brew install zsh

# ----------------------------------------------------------------------------
# code analysis
# ----------------------------------------------------------------------------

brew install --HEAD universal-ctags/universal-ctags/universal-ctags
brew install cloc

# used by fzf grepper preview
brew install highlight

# ----------------------------------------------------------------------------
# git
# ----------------------------------------------------------------------------

brew install git --without-completions
brew install git-extras
brew install hub tig

# ============================================================================
# web
# ============================================================================

brew install yarn

# ============================================================================
# OS
# ============================================================================

brew install mas
brew install gnupg
